### ISSUE TITLE
Support symlinking files in directories.

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-dotfiles#11]
I'll open up a PR later, this should be solvable with:

```yaml
- name: Ensure dotfile directories exist.
  file:
    path: "{{ (dotfiles_home + '/' + item)|dirname }}"
    state: directory
  become: no
  with_items: "{{ dotfiles_files }}"
```
